### ISSUE TITLE
evaluate-binning: line 300: $4: unbound variable

### ISSUE THREAD

**Issue by PhilPalmer** [CAMI-challenge/bbx-binning-evaluation-jd#24]
Hi,
I am trying to benchmark a taxonomic binning pipeline. 
I am first trying to get the binning-evaluation to work with [1st CAMI Challenge Dataset 1 CAMI_low](https://data.cami-challenge.org/participate). I have followed the [simple instructions](https://github.com/CAMI-challenge/bbx-binning-evaluation-jd), having built the docker container [philpalmer/binning-evaluation](https://hub.docker.com/r/philpalmer/binning-evaluation/) and created the relavant input, output and cache folders. 

The input folder contains the following:
<img width="1224" alt="screen shot 2018-09-23 at 10 26 54" src="https://user-images.githubusercontent.com/32334279/45926534-5839b800-bf1b-11e8-9b78-7e65bba2512b.png">

The contents of the biobox.yaml file are:
```
version: 0.10.0
arguments:
  sequences:
    path: /bbx/mnt/input/CAMI_low_RL_S001__insert_270_GoldStandardAssembly.fasta
    id: fas
    type: contig
    format: bioboxes.org:/fasta
  labels:
    path: /bbx/mnt/input/gsa_mapping.binning
    id: lab
    type: binning
    format: bioboxes.org:/binning/binning:0.9/taxbinning
  predictions:
    path: /bbx/mnt/input/gsa_mapping.binning
    id: STRING
    type: binning
    format: bioboxes.org:/binning/binning:0.9/taxbinning
  databases:
    taxonomy:
      path: /bbx/mnt/input/taxonomy
      id: taxonomy
      type: ncbi
      format: bioboxes.org:/taxonomy_ncbi_dumps
```
However on running of the container with the command: ```docker run -v $PWD/input:/bbx/mnt/input:ro -v $PWD/output:/bbx/mnt/output:rw -v $PWD/cache:/bbx/mnt/cache:rw philpalmer/binning-evaluation```
I get the following error **```/opt/cami-evaluate-binning/evaluate-binning: line 300: $4: unbound variable```**
<img width="1436" alt="screen shot 2018-09-23 at 10 32 41" src="https://user-images.githubusercontent.com/32334279/45926580-3bea4b00-bf1c-11e8-81c0-0861607a4e4d.png">

It seems as though while the binning and fasta files specified in biobox.yaml can be found some requried varaibles are not being passed to the script, specifically the prefix:
```
  gold_bin_file=$1
  query_bin_file=$2
  seq_len_file=$3
  prefix=$4
  btype=${5:-taxon}
```

1. Any idea why this is occurng and how it can be resolved?
2. I have manually generated the seq_len_file, shall I try calling the  script inside the container passing the above varaibles as command line arguments?
3. What should the value of prefix be?
4. Should I be using [AMBER](https://github.com/CAMI-challenge/AMBER) instead for benchmarking a taxonomic binning pipeline?

Any help would be much appreciated, many thanks in advance
